import type { Metadata } from "next";
import {
  Geist,
  Geist_Mono,
  Source_Code_Pro,
  Source_Sans_3,
  Inter,
} from "next/font/google";
import "../styles/global.css";
import { Header } from "@/components/global/header/header";

const sourceCodePro = Source_Code_Pro({
  variable: "--font-source-code-pro",
  subsets: ["latin"],
});

const sourceSans3 = Source_Sans_3({
  variable: "--font-source-sans",
  subsets: ["latin"],
});

const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${sourceCodePro.variable} ${sourceSans3.variable} ${inter.variable}`}
      >
        <Header />
        {children}
      </body>
    </html>
  );
}
